### PR TITLE
fixed the whitespace

### PR DESCRIPTION
**Pull request by hildoer**
Thanks again for the quick response. One more favor, can you also do an NPM publish on the 1.2.0+ version?

### CODE REVIEW

**Comment by rragan** [comment]
It is published

**Comment by hildoer** [comment]
Thank you Richard. 

This is the 1.2.0 version that you NPM published?

---

Anthony Hildoer
Principal Engineer
BlueRival Software

text | anthony@bluerival.com
office | 1.800.665.2029
mobile | 720.689.2001
skype | ahildoer
icq | 423790250

**Comment by rragan** [comment]
Yes 1.2.0

**Comment by hildoer** [comment]
Sorry, to bother you again. npmjs.com (https://www.npmjs.com/package/try-require) doesn't seem to see your publish of 1.2.0. Also, npm installs on CLI also only see 1.1.0. Can you try to push again? Maybe bump the version again and include the whitespace changes.

**Comment by rragan** [comment]
OK, published again as 1.2.1 with whitespace changes.

more .npmrc
email=rragan@gmail.com
registry = http://www.npmjs.org
username=rrragan
LM-SJN-00872172:~ rragan$ cd try-require
LM-SJN-00872172:try-require rragan$ npm publish
- try-require@1.2.1

I'm not seeing it show up yet. I guess it may be an npm delay in updating things. Odd though

**Comment by hildoer** [comment]
yeah, it must be an npm issue. thank you so much for helping on this. i will keep tracking it with npm support directly.

**Comment by rragan** [comment]
I will try one more publish from home this evening. Shouldn’t matter but you never know. I double checked that I was not publishing to our internal npm repo (and I was not).

Rich

**Comment by hildoer** [comment]
Richard, looks like npmjs finally updated. Don't know if you continued to try anything, but its up finally. Thank you!

**Comment by rragan** [comment]
Nothing special. It was just weird but cleared up.

**Pull request merged**
